server:
  port: 8082

spring:
  application:
    name: job-scheduler-service
  datasource:
    url: jdbc:postgresql://localhost:5432/jobqueue
    username: jobuser
    password: jobpassword
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
